<template>
  <section class="transcript-box">
    <div class="watermark">Generated by Meetbowl</div>
    <p v-for="line in lines" :key="line.t">
      <time>{{ line.t }}</time>
      <strong>{{ line.who }}</strong>
      <span>{{ line.text }}</span>
    </p>
  </section>
</template>

<script setup>
defineProps({
  lines: { type: Array, required: true },
})
</script>
