<template>
  <!-- 
    [회의 원문(Transcript) UI 컴포넌트]
    STT 엔진이 생성한 대화 기록을 화면에 시각적으로 표시하는 뷰(View) 영역입니다.
  -->
  <section class="transcript-box">
    <!-- 무단 도용 방지 및 AI 생성물 임을 나타내는 워터마크 표시 -->
    <div class="watermark">Generated by Meetbowl</div>
    
    <!-- 
      부모 컴포넌트로부터 전달받은 대화 내역(lines)을 반복 렌더링합니다.
      각 줄은 발화 시간(time), 화자(who), 발화 내용(text)으로 구성됩니다.
    -->
    <p v-for="line in lines" :key="line.t">
      <time>{{ line.t }}</time>
      <strong>{{ line.who }}</strong>
      <span>{{ line.text }}</span>
    </p>
  </section>
</template>

<script setup>
/**
 * [컴포넌트 속성(Props) 정의]
 * @property {Array} lines - 렌더링할 대화 데이터 배열. 각 객체는 { t: 시간, who: 화자, text: 내용 } 형태를 기대합니다.
 */
defineProps({
  lines: { type: Array, required: true },
})
</script>
